### ISSUE TITLE
Unable to Push Branch

### ISSUE THREAD

**Issue by dmholtz** [craft-coder/UbungVersionsverwaltung#3]
Dear Mr Feilhauer,

I participated in the git exercise on version control and tried to push my local feature branch to the remote repo. Unfortunately, the following error message was displayed:

```
remote: Permission to craft-coder/UbungVersionsverwaltung.git denied to dmholtz.
fatal: unable to access 'https://github.com/craft-coder/UbungVersionsverwaltung/': The requested URL returned error: 403
```

I think, students cannot push any commits to the repo unless you give us the collaborator status on github. Or might there be another reason for this issue?

Best regards
dmholtz

**Comment by craft-coder** [comment]
Thanks for your comment.
Unfortunatelly I cannot grant "public" permissions to collaborate. 
I'm happy to give access to anyone who's interessted.
